### ISSUE TITLE
Document the motivation for this crate?

### ISSUE THREAD

**Issue by oconnor663** [smol-rs/parking#24]
It would be nice for the readme to document why callers might want to use this crate over `std::thread::park`. I have a vague idea that the latter doesn't compose well, like if an inner library and an outer library both think they can park and unpark the current thread, and the inner library ends up consuming the outer library's tokens? But I don't remember where I read that, and I'm not sure it's correct. If that is the right idea, is it fair to say that _no one_ should use `std::thread::park`? Should it be deprecated?

**Comment by notgull** [comment]
cc https://github.com/smol-rs/parking/issues/7

It would be nice to add this to documentation.
