### ISSUE TITLE
Specify the advantages that this crate has over the standard library thread::park()

### ISSUE THREAD

**Issue by notgull** [smol-rs/parking#7]
It is unclear from looking through the docs and the readme of this crate what advantages it has over using the standard library [`std::thread::park()`](https://doc.rust-lang.org/std/thread/fn.park.html) and [`std::thread::Thread::unpark()`](https://doc.rust-lang.org/std/thread/struct.Thread.html#method.unpark) functions. A cursory glance over the codebase seems to indicate that it uses the same code that the [generic thread-parking function](https://github.com/rust-lang/rust/blob/master/library/std/src/sys_common/thread_parker/generic.rs) uses, which means that it allocates memory for something threads already have built-in. The main advantage from what I can glean is that this algorithm defeats spurious wakeups, which the standard library doesn't guarantee. However, [all](https://github.com/rust-lang/rust/blob/master/library/std/src/sys_common/thread_parker/generic.rs#L53) [three](https://github.com/rust-lang/rust/blob/master/library/std/src/sys_common/thread_parker/futex.rs#L55) [implementations](https://github.com/rust-lang/rust/blob/master/library/std/src/sys/windows/thread_parker.rs#L120) already have guards against spurious wakeups.

**Comment by taiki-e** [comment]
https://github.com/smol-rs/futures-lite/pull/54#issuecomment-1183361388
